export const categoriesData = [
  {
    name: 'Dogs',
    description: 'Loyal, playful companions for every family.',
    icon: 'Dog',
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&q=80',
    order: 1,
  },
  {
    name: 'Cats',
    description: 'Independent, affectionate feline friends.',
    icon: 'Cat',
    image: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=800&q=80',
    order: 2,
  },
  {
    name: 'Birds',
    description: 'Colorful, melodious companions for your home.',
    icon: 'Bird',
    image: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&q=80',
    order: 3,
  },
  {
    name: 'Rabbits',
    description: 'Gentle, fluffy friends full of energy.',
    icon: 'Rabbit',
    image: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=800&q=80',
    order: 4,
  },
  {
    name: 'Fish',
    description: 'Serene aquatic pets for a calm home.',
    icon: 'Fish',
    image: 'https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?w=800&q=80',
    order: 5,
  },
  {
    name: 'Exotic Pets',
    description: 'Unique and fascinating companions.',
    icon: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1621844831281-5c5f0a2b8c8b?w=800&q=80',
    order: 6,
  },
];

export const petsSeed = [
  {
    name: 'Rocky',
    breed: 'Labrador Retriever',
    categoryName: 'Dogs',
    age: '3 months',
    gender: 'Male',
    color: 'Golden',
    weight: '5 kg',
    price: 25000,
    vaccinationStatus: 'Vaccinated',
    healthStatus: 'Excellent',
    temperament: 'Friendly, Playful, Loyal',
    foodPreference: 'Puppy dry food, boiled chicken',
    description: 'Rocky is a super friendly Labrador puppy who loves to play fetch and cuddle.',
    additionalNotes: 'Dewormed and first vaccination completed.',
    images: [
      'https://images.unsplash.com/photo-1591160690555-5debfba289f0?w=900&q=80',
      'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=900&q=80',
    ],
    videoUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm',
    featured: true,
  },
  {
    name: 'Bella',
    breed: 'Golden Retriever',
    categoryName: 'Dogs',
    age: '2 months',
    gender: 'Female',
    color: 'Cream',
    weight: '4 kg',
    price: 28000,
    vaccinationStatus: 'Partially Vaccinated',
    healthStatus: 'Excellent',
    temperament: 'Gentle, Affectionate',
    foodPreference: 'Premium puppy kibble',
    description: 'Bella is an adorable Golden Retriever puppy with a heart-melting personality.',
    images: ['https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=900&q=80'],
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    featured: true,
  },
  {
    name: 'Max',
    breed: 'German Shepherd',
    categoryName: 'Dogs',
    age: '4 months',
    gender: 'Male',
    color: 'Black & Tan',
    weight: '9 kg',
    price: 32000,
    vaccinationStatus: 'Vaccinated',
    healthStatus: 'Excellent',
    temperament: 'Intelligent, Protective, Active',
    foodPreference: 'High protein puppy food',
    description: 'Max is a confident and intelligent German Shepherd, great for families.',
    images: ['https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=900&q=80'],
  },
  {
    name: 'Coco',
    breed: 'Persian Cat',
    categoryName: 'Cats',
    age: '5 months',
    gender: 'Female',
    color: 'White',
    weight: '2 kg',
    price: 18000,
    vaccinationStatus: 'Vaccinated',
    healthStatus: 'Excellent',
    temperament: 'Calm, Affectionate',
    foodPreference: 'Premium wet & dry cat food',
    description: 'Coco is a fluffy Persian beauty with a calm and loving temperament.',
    images: ['https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=900&q=80'],
    videoUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm',
    featured: true,
  },
  {
    name: 'Simba',
    breed: 'Maine Coon',
    categoryName: 'Cats',
    age: '6 months',
    gender: 'Male',
    color: 'Brown Tabby',
    weight: '3.5 kg',
    price: 22000,
    vaccinationStatus: 'Vaccinated',
    healthStatus: 'Excellent',
    temperament: 'Playful, Social',
    foodPreference: 'High protein cat food',
    description: 'Simba is a majestic Maine Coon kitten, known for his size and gentle nature.',
    images: ['https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?w=900&q=80'],
  },
  {
    name: 'Kiwi',
    breed: 'African Grey Parrot',
    categoryName: 'Birds',
    age: '8 months',
    gender: 'Unknown',
    color: 'Grey',
    weight: '450 g',
    price: 45000,
    vaccinationStatus: 'Not Vaccinated',
    healthStatus: 'Excellent',
    temperament: 'Intelligent, Talkative',
    foodPreference: 'Seed mix, fruits, vegetables',
    description: 'Kiwi is a highly intelligent African Grey Parrot that can mimic words.',
    images: ['https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=900&q=80'],
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    featured: true,
  },
  {
    name: 'Sunny',
    breed: 'Sun Conure',
    categoryName: 'Birds',
    age: '4 months',
    gender: 'Male',
    color: 'Yellow & Orange',
    weight: '110 g',
    price: 15000,
    vaccinationStatus: 'Not Vaccinated',
    healthStatus: 'Excellent',
    temperament: 'Energetic, Social',
    foodPreference: 'Fruits, seeds, pellets',
    description: 'Sunny is a vibrant Sun Conure full of energy and color.',
    images: ['https://images.unsplash.com/photo-1544923246-77307dd654cb?w=900&q=80'],
  },
  {
    name: 'Snowy',
    breed: 'Holland Lop',
    categoryName: 'Rabbits',
    age: '3 months',
    gender: 'Female',
    color: 'White',
    weight: '1.2 kg',
    price: 8000,
    vaccinationStatus: 'Vaccinated',
    healthStatus: 'Excellent',
    temperament: 'Gentle, Calm',
    foodPreference: 'Hay, pellets, fresh vegetables',
    description: 'Snowy is a soft and gentle Holland Lop rabbit perfect for a cozy home.',
    images: ['https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=900&q=80'],
    videoUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm',
    featured: true,
  },
  {
    name: 'Nemo',
    breed: 'Betta Fish',
    categoryName: 'Fish',
    age: '6 months',
    gender: 'Male',
    color: 'Red & Blue',
    weight: '10 g',
    price: 1200,
    vaccinationStatus: 'Not Vaccinated',
    healthStatus: 'Excellent',
    temperament: 'Territorial, Calm',
    foodPreference: 'Betta pellets, bloodworms',
    description: 'Nemo is a vibrant Betta fish with stunning colors, perfect for a home aquarium.',
    images: ['https://images.unsplash.com/photo-1520302519106-b8b3fa4ea6f1?w=900&q=80'],
  },
  {
    name: 'Spike',
    breed: 'Bearded Dragon',
    categoryName: 'Exotic Pets',
    age: '10 months',
    gender: 'Male',
    color: 'Orange',
    weight: '350 g',
    price: 12000,
    vaccinationStatus: 'Not Vaccinated',
    healthStatus: 'Excellent',
    temperament: 'Docile, Curious',
    foodPreference: 'Insects, leafy greens',
    description: 'Spike is a friendly Bearded Dragon, easy to handle and great for beginners.',
    images: ['https://images.unsplash.com/photo-1590534247854-e97d5e3feef8?w=900&q=80'],
    featured: true,
  },
  {
    name: 'Luna',
    breed: 'Siberian Husky',
    categoryName: 'Dogs',
    age: '3 months',
    gender: 'Female',
    color: 'Black & White',
    weight: '6 kg',
    price: 35000,
    vaccinationStatus: 'Vaccinated',
    healthStatus: 'Excellent',
    temperament: 'Energetic, Friendly, Vocal',
    foodPreference: 'High energy puppy food',
    description: 'Luna is a stunning Husky puppy with striking blue eyes and boundless energy.',
    images: ['https://images.unsplash.com/photo-1547407139-3c921a71905c?w=900&q=80'],
  },
  {
    name: 'Milo',
    breed: 'British Shorthair',
    categoryName: 'Cats',
    age: '4 months',
    gender: 'Male',
    color: 'Grey',
    weight: '2.5 kg',
    price: 20000,
    vaccinationStatus: 'Vaccinated',
    healthStatus: 'Excellent',
    temperament: 'Calm, Independent',
    foodPreference: 'Premium dry cat food',
    description: 'Milo is a plush, round-faced British Shorthair with a laid-back personality.',
    images: ['https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=900&q=80'],
  },
];
